modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/OrderedChaos-Dev/HomeIsWhereTheHearthIs/issues"

[[mods]]
	modId="homeiswherethehearthis"
	version="${version}"
	displayName="Home Is Where The Hearth Is"
	displayURL="https://www.orderedchaos.dev/"
	logoFile="https://github.com/OrderedChaos-Dev/HomeIsWhereTheHearthIs/issues.png"
	authors="ordered_chaos_dev"
	description='''
		Simple chimneys and fireplaces for your home
	'''
[[dependencies.homeiswherethehearthis]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.homeiswherethehearthis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
